function q_ddot = NE_get_q_ddot(q, q_dot, g0, DHTable, u, m, I, r_CoM, Fv, Fs)
    zero_q = zeros(size(q));
    n = NE_dynamics( ...
        q, ...
        q_dot, ...
        zero_q, ...
        g0, ...
        DHTable, ...
        m, ...
        I, ...
        r_CoM, ...
        Fv, ...
        Fs ...
    );

    zero_g = zeros(3, 1);
    identity = eye(length(q));
    for i = 1:size(q)
        M(:, i) = NE_dynamics( ...
            q, ...
            zero_q, ...
            identity(:, i), ...
            zero_g, ...
            DHTable, ...
            m, ...
            I, ...
            r_CoM, ...
            Fv, ...
            Fs ...
        );
    end
    q_ddot = M\ (u - n);
end