function [M, C, G] = NE_get_model(q, q_dot, g0, DHTable, params)
    zero_g = [0; 0; 0];
    zero_q = zeros(size(q));
    identity = eye(length(q));

    for i = 1:size(q)
        M(:, i) = simplify(NE_Dynamics( ...
            q, ...
            zero_q, ...
            identity(:, i), ...
            zero_g, ...
            DHTable, ...
            params.m, ...
            params.I, ...
            params.r_CoM, ...
            params.Fv ...
        ));
    end
    M = simplify(M);

    C = NE_Dynamics( ...
        q, ...
        q_dot, ...
        zero_q, ...
        zero_g, ...
        DHTable, ...
        params.m, ...
        params.I, ...
        params.r_CoM, ...
        params.Fv ...
    );
    C = simplify(C);

    G = NE_Dynamics( ...
        q, ...
        zero_q, ...
        zero_q, ...
        g0, ...
        DHTable, ...
        params.m, ...
        params.I, ...
        params.r_CoM, ...
        params.Fv ...
    );
    G = simplify(G);
end